let data=[
  {id:1,
    image:"https://ii2.pepperfry.com/media/catalog/product/e/f/494x544/efflino-study-table-in-white-colour-by-bluewud-efflino-study-table-in-white-colour-by-bluewud-ne00xv.jpg",
    desc:"Efflino Study Table In White Finish",
    company:"bluewud",
    price:"₹ 2,738",
    discount:"30% Off"
  },
  {id:2,
    image:"https://ii3.pepperfry.com/media/catalog/product/g/u/494x544/gustowe-study-table-in-white-finish-by-bluewud-gustowe-study-table-in-white-finish-by-bluewud-7prrwd.jpg",
    desc:"Gustowe Study TAble in White",
    company:"bluewud",
    price:"₹ 2,831",
    discount:"30% Off"
  },
  {id:3,
    image:"https://ii2.pepperfry.com/media/catalog/product/c/l/494x544/clonard-study-table-in-wenge-finish-by-bluewud-clonard-study-table-in-wenge-finish-by-bluewud-2ocuda.jpg",
    desc:"Clonard Study Table in Wenge",
    company:"Woodbuzz",
    price:"₹ 2,831",
    discount:"30% Off"
  },
  {id:4,
    image:"https://ii3.pepperfry.com/media/catalog/product/o/f/494x544/office-table-office-table-v2oabe.jpg",
    desc:"Study table in Walnut Finish",
    company:"Mintwud",
    price:"₹ 2,899",
    discount:"30% Off"
  },
  {id:5,
    image:"https://ii1.pepperfry.com/media/catalog/product/s/k/494x544/sky-wall-mounted-large-multipurpose-table-in-mangfall-beech-finish-by-woodware-sky-wall-mounted-larg-wmydlg.jpg",
    desc:"Sky Wall Mounted Large Table",
    company:"bluewud",
    price:"₹ 3,450",
    discount:"30% Off"
  },
  {id:6,
    image:"https://ii2.pepperfry.com/media/catalog/product/h/a/494x544/hayao-study-table-with-drawer-in-wenge-finish---mintwud-by-pepperfry-hayao-study-table-with-drawer-i-el4ino.jpg",
    desc:"Hayao Study Table",
    company:"Woodbuzz",
    price:"₹ 3,599",
    discount:"30% Off"
  },
  {id:7,
    image:"https://ii2.pepperfry.com/media/catalog/product/e/f/494x544/efflino-study-table-desk-in-wenge---white-finish-by-bluewud-efflino-study-table-desk-in-wenge---whit-rnykak.jpg",
    desc:"Efflino Study Table Desk",
    company:"bluewud",
    price:"₹ 4,499",
    discount:"30% Off"
  },
  {id:8,
    image:"https://ii3.pepperfry.com/media/catalog/product/a/m/494x544/amica-compact-study-table-in-dark-brown-finish-by-woodware-amica-compact-study-table-in-dark-brown-f-z5o6oi.jpg",
    desc:"Amica Compact Study Table",
    company:"Mintwud",
    price:"₹ 5,699",
    discount:"30% Off"
  },
  {id:9,
    image:"https://ii2.pepperfry.com/media/catalog/product/d/u/494x544/duke-writing-table-in-frosty-white-and-ocean-green-colour-by-woodbuzz-duke-writing-table-in-frosty-w-znkbdo.jpg",
    desc:"Duke Writing Table",
    company:"bluewud",
    price:"₹ 6,899",
    discount:"30% Off"
  },
  {id:10,
    image:"https://ii2.pepperfry.com/media/catalog/product/d/u/494x544/duke-study-table-in-frosty-white-and-pink-colour-by-woodbuzz-duke-study-table-in-frosty-white-and-pi-keugsm.jpg",
    desc:"Duke Study Table",
    company:"Woodbuzz",
    price:"₹ 5,699",
    discount:"30% Off"
  },
  {id:11,
    image:"https://ii3.pepperfry.com/media/catalog/product/t/a/494x544/takaya-study-table-in-walnut-brown-finish-by-mintwud-takaya-study-table-in-walnut-brown-finish-by-mi-4gsjlt.jpg",
    desc:"Takaya Study Table",
    company:"Mintwud",
    price:"₹ 3,499",
    discount:"30% Off"
  },
  {id:12,
    image:"https://ii1.pepperfry.com/media/catalog/product/v/e/494x544/verto-large-height-adjustable-writing-table-in-asian-dark-by-woodware-verto-large-height-adjustable--tueuop.jpg",
    desc:"Verto Large Study Table",
    company:"bluewud",
    price:"₹ 5,599",
    discount:"30% Off"
  },
  {id:13,
    image:"https://ii3.pepperfry.com/media/catalog/product/f/e/494x544/felipe-engineered-wood-study-table-frosty-white-finish-by-das-d-cor-felipe-engineered-wood-study-tab-qtb3ec.jpg",
    desc:"Felipe Study Table",
    company:"Woodbuzz",
    price:"₹ 9,999",
    discount:"30% Off"
  },
  {id:14,
    image:"https://ii2.pepperfry.com/media/catalog/product/n/y/494x544/nyoko-study-table-in-dark-oak-finish-by-mintwud-nyoko-study-table-in-dark-oak-finish-by-mintwud-fjscju.jpg",
    desc:"Nyoko Study Table",
    company:"Mintwud",
    price:"₹ 6,599",
    discount:"30% Off"
  },
  {id:1,
    image:"https://ii2.pepperfry.com/media/catalog/product/e/f/494x544/efflino-study-table-in-white-colour-by-bluewud-efflino-study-table-in-white-colour-by-bluewud-ne00xv.jpg",
    desc:"Efflino Study Table In White Finish",
    company:"bluewud",
    price:"₹ 2,738",
    discount:"30% Off"
  },
  {id:1,
    image:"https://ii2.pepperfry.com/media/catalog/product/e/f/494x544/efflino-study-table-in-white-colour-by-bluewud-efflino-study-table-in-white-colour-by-bluewud-ne00xv.jpg",
    desc:"Efflino Study Table In White Finish",
    company:"bluewud",
    price:"₹ 2,738",
    discount:"30% Off"
  },
  {id:1,
    image:"https://ii2.pepperfry.com/media/catalog/product/e/f/494x544/efflino-study-table-in-white-colour-by-bluewud-efflino-study-table-in-white-colour-by-bluewud-ne00xv.jpg",
    desc:"Efflino Study Table In White Finish",
    company:"bluewud",
    price:"₹ 2,738",
    discount:"30% Off"
  },
  {id:1,
    image:"https://ii2.pepperfry.com/media/catalog/product/e/f/494x544/efflino-study-table-in-white-colour-by-bluewud-efflino-study-table-in-white-colour-by-bluewud-ne00xv.jpg",
    desc:"Efflino Study Table In White Finish",
    company:"bluewud",
    price:"₹ 2,738",
    discount:"30% Off"
  },
  {id:1,
    image:"https://ii2.pepperfry.com/media/catalog/product/e/f/494x544/efflino-study-table-in-white-colour-by-bluewud-efflino-study-table-in-white-colour-by-bluewud-ne00xv.jpg",
    desc:"Efflino Study Table In White Finish",
    company:"bluewud",
    price:"₹ 2,738",
    discount:"30% Off"
  },
  {id:1,
    image:"https://ii2.pepperfry.com/media/catalog/product/e/f/494x544/efflino-study-table-in-white-colour-by-bluewud-efflino-study-table-in-white-colour-by-bluewud-ne00xv.jpg",
    desc:"Efflino Study Table In White Finish",
    company:"bluewud",
    price:"₹ 2,738",
    discount:"30% Off"
  },
  {id:1,
    image:"https://ii2.pepperfry.com/media/catalog/product/e/f/494x544/efflino-study-table-in-white-colour-by-bluewud-efflino-study-table-in-white-colour-by-bluewud-ne00xv.jpg",
    desc:"Efflino Study Table In White Finish",
    company:"bluewud",
    price:"₹ 2,738",
    discount:"30% Off"
  },
  {id:1,
    image:"https://ii2.pepperfry.com/media/catalog/product/e/f/494x544/efflino-study-table-in-white-colour-by-bluewud-efflino-study-table-in-white-colour-by-bluewud-ne00xv.jpg",
    desc:"Efflino Study Table In White Finish",
    company:"bluewud",
    price:"₹ 2,738",
    discount:"30% Off"
  },
  {id:1,
    image:"https://ii2.pepperfry.com/media/catalog/product/e/f/494x544/efflino-study-table-in-white-colour-by-bluewud-efflino-study-table-in-white-colour-by-bluewud-ne00xv.jpg",
    desc:"Efflino Study Table In White Finish",
    company:"bluewud",
    price:"₹ 2,738",
    discount:"30% Off"
  },
  {id:1,
    image:"https://ii2.pepperfry.com/media/catalog/product/e/f/494x544/efflino-study-table-in-white-colour-by-bluewud-efflino-study-table-in-white-colour-by-bluewud-ne00xv.jpg",
    desc:"Efflino Study Table In White Finish",
    company:"bluewud",
    price:"₹ 2,738",
    discount:"30% Off"
  },
  {id:1,
    image:"https://ii2.pepperfry.com/media/catalog/product/e/f/494x544/efflino-study-table-in-white-colour-by-bluewud-efflino-study-table-in-white-colour-by-bluewud-ne00xv.jpg",
    desc:"Efflino Study Table In White Finish",
    company:"bluewud",
    price:"₹ 2,738",
    discount:"30% Off"
  },
  {id:1,
    image:"https://ii2.pepperfry.com/media/catalog/product/e/f/494x544/efflino-study-table-in-white-colour-by-bluewud-efflino-study-table-in-white-colour-by-bluewud-ne00xv.jpg",
    desc:"Efflino Study Table In White Finish",
    company:"bluewud",
    price:"₹ 2,738",
    discount:"30% Off"
  },
  {id:1,
    image:"https://ii2.pepperfry.com/media/catalog/product/e/f/494x544/efflino-study-table-in-white-colour-by-bluewud-efflino-study-table-in-white-colour-by-bluewud-ne00xv.jpg",
    desc:"Efflino Study Table In White Finish",
    company:"bluewud",
    price:"₹ 2,738",
    discount:"30% Off"
  },
  {id:1,
    image:"https://ii2.pepperfry.com/media/catalog/product/e/f/494x544/efflino-study-table-in-white-colour-by-bluewud-efflino-study-table-in-white-colour-by-bluewud-ne00xv.jpg",
    desc:"Efflino Study Table In White Finish",
    company:"bluewud",
    price:"₹ 2,738",
    discount:"30% Off"
  },
  {id:1,
    image:"https://ii2.pepperfry.com/media/catalog/product/e/f/494x544/efflino-study-table-in-white-colour-by-bluewud-efflino-study-table-in-white-colour-by-bluewud-ne00xv.jpg",
    desc:"Efflino Study Table In White Finish",
    company:"bluewud",
    price:"₹ 2,738",
    discount:"30% Off"
  },
  {id:1,
    image:"https://ii2.pepperfry.com/media/catalog/product/e/f/494x544/efflino-study-table-in-white-colour-by-bluewud-efflino-study-table-in-white-colour-by-bluewud-ne00xv.jpg",
    desc:"Efflino Study Table In White Finish",
    company:"bluewud",
    price:"₹ 2,738",
    discount:"30% Off"
  }
]